sudo: false
language: ruby
env:
  global:
  - GH_REF: github.com/NashMiao/ontology-python-sdk-docs.git
  - secure: ghV7GsiBDt24inNeZ/BVOWoG1NAGYzEyzi8hpq3kHvtEOMjS9XrUXZhhKO9wprAw2t7EH/gjfJnwv0dkTt+sSOv9bYH5NYxE5cM2JO5GC4RlX16GNHus5UbiR6DHm3TztxbuiV9W3+Dri+NM8bUam0CUERcMljoGUyCwwQPnRt3998M5Yt5h0DhoErVqK7EyMOzLe3jbtRKMxQggImLPTauBxPEFnez7B/sIVBQ3UMhSANV45Ta90XdaLkMA7XmlE76QO6iBStCW3svuuDpyl1GyHAK9vYHm5ORmyVwyCaA6ySIK74vxDHztyau+cT37ywfgQESc0TDs7+qVhZ8fZCp3iwcJLdtbEBrdhVSwVjUlaVuD0zOnxSvDK6nbPtXjLUV6Xc0pa6Hyz91en8zYBOlK1o+FIl5o3ywJBkYxxfSe6gc7V9M/kcwJ+Qr4xpIQeYCweylTJMnz3J8XXm/pgVklYJADziH4NAbQ6dQxlJne0CMffm9muqMbkcYd3ctxgM7tdwuBKAlXrL4Xxtqysc8JUXdcN4IZ3vw2mxnbMGCKYIcS5MvVzsEucCrEmAZK2Ec0ElhuyI25lzXfIkG4ZVTGPX2r2PhhEawUY+7aQPPVxN4Kcwmu6zdy2BA/FPcDSE6XuvKtdJC2dtCaKv9OLTrizHL/5+EATECNWsbQWd0=
rvm:
- 2.4.0
branches:
  only:
  - master
cache: bundler
before_script:
- git clone https://${GH_TOKEN}@${GH_REF} -b gh-pages --depth=1 build
script:
- bundle exec middleman build --clean
after_script:
- cd ./build
- git config user.name "travis-bot"
- git config user.email "wdx7266@vip.qq.com"
- git add .
- git commit -m "update page automatically"
- git push
