sudo: false
language: ruby
env:
  global:
  - GH_REF: github.com/NashMiao/ontology-python-sdk-docs.git
  - secure: f/HAaX1kaw25du3nj2Lqo2+4P7YNo7jIqMDXC2XTAYdTMpXgZwo66zH8O0zi4TMQBG6FjtVX1/reTKioMKTV3MG65n5U/OvvLqfD3MpQAPA00QvVOJAmPF6sJT5J9aspph9v6uLRBe+8CRqrdFI+STq74SJVHMzUFVjpnitpJfua5+Ni8EWZiZXsr+EFo7MuF7UYQ1/lOoCYq9NUsqWek5fjC9ZhjZknsNv64zGjXZbkNNnCdx4Wxms1I97wjaV+gimrBSGCBEord7Kc97WqWaIQqHRqFnqWDFlcxj9/cds7roXzik9gZOGEb/83HEVwThKLhp1v6xtPc9OgJiP7u34DJ9nYtjfbke/+SBXmnomly4deLnY+zNhp7bsoIt7JIRr3yx4pdFKtIbi0ZkqSgUazjbIAlo8FGCr938rlRb5qD4v6TDYy8f+DTJSgXrlLacJzEufVluPZrUmD4gGgowOv78dZPRUW/SBcXBkvcMEUnYGQpKWhr2uVBpfJixresgidp4lETgH9aRHkHvoF6i2y1XXcOdet6R5kEqYSzawtf28mdVF89AMjZNwhSZhgbYdcTOtFbQg18ZbQ03OEba1YDo6sJJIB1qdGrJa3VP7ShcP/T4H9yNRKNdRf9zUidSe4Ilfkulwk4EF2bCtf5oXHBObahQ0ytq16pZh6eKA=
rvm:
- 2.4.0
branches:
  only:
  - master
cache: bundler
before_script:
- git config --global user.name "travis-bot"
- git config --global user.email "wdx7266@vip.qq.com"
- git clone https://${GH_TOKEN}@${GH_REF} -b gh-pages --depth=1 build
script:
- bundle exec middleman build --clean
after_script:
- cd ./build
- git add .
- git commit -m "update page automatically"
- git push
